config/routes.rb
PhoneAppAngular::Application.routes.draw do

resources :phones
 root 'static_pages#index'
 # get 'phones', to: 'static_pages#phones'

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phone }
      else
        format.html { render action: 'new' }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params[:phone]
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "phonemaker"}
  %head
    %title Phone App
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div{"ng-view" => ""}
      = yield

app/views/phones/_form.html.haml
= form_for @phone do |f|
  - if @phone.errors.any?
    #error_explanation
      %h2= "#{pluralize(@phone.errors.count, "error")} prohibited this phone from being saved:"
      %ul
        - @phone.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/phones/edit.html.haml
%h1 Editing phone

= render 'form'

= link_to 'Show', @phone
\|
= link_to 'Back', phones_path

app/views/phones/index.html.haml
%h1 Listing phones

%table
  %tr
    %th
    %th
    %th

  - @phones.each do |phone|
    %tr
      %td= link_to 'Show', phone
      %td= link_to 'Edit', edit_phone_path(phone)
      %td= link_to 'Destroy', phone, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Phone', new_phone_path

app/views/phones/new.html.haml
%h1 New phone

= render 'form'

= link_to 'Back', phones_path

app/views/phones/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_phone_path(@phone)
\|
= link_to 'Back', phones_path

app/views/static_pages/index.html.haml
%h1 StaticPages#index
%p Find me in app/views/static_pages/index.html.haml